### ISSUE TITLE
Could I use this in gulp?

### ISSUE THREAD

**Issue by dajulia3** [pact-foundation/pact-node#1]
I was thinking of trying to use this as part of a build tool like grunt, but am having trouble figuring out how to programmatically run the pact broker via your wrapper. Could you offer any guidance? 

Thank you!

**Comment by mboudreau** [comment]
you can use this with Gulp or Grunt.  For Grunt, I recommend you use the [grunt-pact project to make your life easier](pact-foundation/grunt-pact).

After pact has been started, this is where you can run scripts that sets your contract.  [There's an example here, but it's a bit out of date](https://github.com/DiUS/pact-consumer-js-dsl/tree/master/example/nodejs).  Sorry for this, I really do need to document more and make it easier for people to get started with it.
