### ISSUE TITLE
Windows 10 Long Pathing Issue

### ISSUE THREAD

**Issue by AndrewSerie** [pact-foundation/pact-node#101]
We are running `pact-node 6.19.6` `karma-pact 2.1.5` and `pact-web 5.9.1`

Is there a max path length requirement? I seem to be having issues with running pact tests with directories that are long.  After I change the length of the directory names, pact-node starts up successfully.  

After running on windows machine with long path names:
```
Creating Pact Server with options:
    consumer = ux,
    provider = core,
    logLevel = debug,
    dir = C:\Users\aserie\source\repos\my-long-repo-name\long-workspace-name\apps\app1\pacts,
    log = C:\Users\aserie\source\repos\my-long-repo-name\long-workspace-name\apps\app1\logs\pact.log,
    port = 1234,
    host = localhost,
    pactFileWriteMode = overwrite,
    ssl = false,
    cors = false
[2018-07-16T14:34:57.615Z]  INFO: pact-node@6.19.6/10772 on aserie: Created 'standalone\win32-1.52.1\bin\pact-mock-service.bat service --consumer 'ux' --provider 'corerunner' --log-level 'DEBUG' --pact_dir 'C:\Users\aserie\source\repos\my-long-repo-name\long-workspace-name\apps\app1\pacts' --log 'C:\Users\aserie\source\repos\my-long-repo-name\long-workspace-name\apps\app1\logs\pact.log' --port '1234' --host 'localhost' --pact-file-write-mode 'overwrite'' process with PID: 6308
(node:10772) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
[2018-07-16T14:35:04.536Z]  WARN: pact-node@6.19.6/10772 on aserie: Pact exited with code 1.
[2018-07-16T14:35:04.536Z]  INFO: pact-node@6.19.6/10772 on aserie: Removing Pact with PID: 6308
ERROR: The process "6308" not found.                                                               
```

Simply making the directory smaller will start pact-node without it exiting with code 1.
Shorter directory name: C:\Users\aserie\source\repos\my-repo\workspace\apps\app1\...

Similar whitespace Issue - #90

**Comment by mefellows** [comment]
Yep, Windows has a hard maximum length on file names - so the longer your project path, coupled with the length of paths results in all kinds of madness. Absolute madness.

@mboudreau I'm thinking perhaps we could almost detect this situation, and log out a warning so people know the reason as to _why_ it failed - thoughts?

**Comment by mboudreau** [comment]
@mefellows I can see what I can do, but I'm not sure if there's a way of really figuring out why the app crashed, other than place a windows path 'check' before it starts running.  I'm sure others have hit this issue...

**Comment by AndrewSerie** [comment]
I understand the 260 chars but my pathing to the app folder is ~ 80 chars which leaves me with another 180 chars.  Is it because the binary is getting buried inside of the npm package? I dont see this as a viable option if pathing to my app's working directory has to be < ~70

**Comment by mefellows** [comment]
@AndrewSerie short answer - yes. Have a look through the issues for more background as we've been through this multiple times. Without significantly re-architecting things (which we are doing btw, it just takes time) this won't be able to change. We're certainly open to new suggestions.

If pathing is an issue for you, have a look at installing the [binaries](https://github.com/pact-foundation/pact-ruby-standalone/releases) onto the path manually, and then [specifying the location](https://github.com/pact-foundation/pact-node/#pact-download-location) to the pact-node package. This should give you the extra breathing room.

**Comment by mboudreau** [comment]
I've added a warning in Pact on initialization to let the user know if they have windows long path enable or not, version 6.19.7.  It will warn the user about the issue and how to solve it by [pointing them to a registry fix ](https://github.com/pact-foundation/pact-node/blob/master/README.md#enable-long-paths).

This is really the best I can do, the rest is on Windows to fix.

**Comment by mefellows** [comment]
I think this is perfect @mboudreau!
