### ISSUE TITLE
Verifier doesnt support HTTPS broker URLs 

### ISSUE THREAD

**Issue by jfnavin** [pact-foundation/pact-node#11]
When running `pact.verifyPacts()` the `pactUrls` array doesn't seem to support HTTPS broker URLs.

Looking at `pact-provider-verifier-darwin/lib/app/lib/pact/provider_verifier/app.rb:88` it appears to parse the URL and then re-construct it with a HTTP scheme.

**Comment by mefellows** [comment]
Hi @jfnavin, I've raised a bug over at pact-foundation/pact-provider-verifier. I'll try to take a look at that this week (feel free to send through a PR!)

**Comment by jfnavin** [comment]
Thanks @mefellows! If I get some time today I'll take a look at raising a PR.

**Comment by mefellows** [comment]
Already in it. Should have a release out within the hour (via my personal
office aka Metro trains)

**Comment by jfnavin** [comment]
Awesome! Cheers.

**Comment by mefellows** [comment]
Released v4.4.2 which fixes this. Thanks for the bug report @jfnavin.
