### ISSUE TITLE
Please update to ruby-standalone 1.58.0

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-node#113]
Or whatever the latest version is by the time this gets done.

This version moves the pact broker pact retrieval code in to the ruby code. This is to support the new "pending pacts" feature, and to fix the "have to configure the SSL for both node and Ruby" issue.

The new command line parameters are:

```
      [--pact-broker-base-url=PACT_BROKER_BASE_URL]                  
        # Base URL of the Pact Broker from which to retrieve the pacts.
      [--provider=PROVIDER]                                          
      [--consumer-version-tag=TAG]                                   
        # Retrieve the latest pacts with this consumer version tag. 
          Used in conjunction with --provider. May be specified multiple times.
```

The existing `--broker-username` and `--broker-password` will be maintained.

**Comment by mboudreau** [comment]
Updated to latest, 1.61.1, released version of pact-node 6.20.0.
