### ISSUE TITLE
TypeScript errors due to usage of bunyan dependency types

### ISSUE THREAD

**Issue by samuelmaddock** [pact-foundation/pact-node#115]
@pact-foundation/pact-node version: 6.19.11
bunyan version: 1.8.12
@types/bunyan version: 1.8.2

The usage of the bunyan dependency seems incorrect in [logger.ts](https://github.com/pact-foundation/pact-node/blob/master/src/logger.ts#L8).

TypeScript complains that `Type 'typeof Logger' is not a constructor function type.` in logger.d.ts from the compiled module. The fix seems to be
```diff
/// <reference types="bunyan" />
import * as bunyan from "bunyan";
-export declare class Logger extends bunyan {
+export declare class Logger extends bunyan.default {
    time(action: string, startTime: number): void;
    readonly logLevelName: string;
}
```

For now, I'm including the following code to fix this type issue locally
```ts
declare module 'bunyan'
```

**Comment by mboudreau** [comment]
Hm, that's unfortunate. I'll have to update our logger to something that supports typescript better.

**Comment by Byron-TW** [comment]
I am experiencing the same issue, which makes it seemingly impossible to use typescript with pact (v7.2.0) in dev dependencies.

The fix suggested above works (i.e. adding `.default`), but I don't know how the local fix with `declare module 'bunyan'` is supposed to be applied.

**Comment by samuelmaddock** [comment]
@Byron-TW I created a type declaration file (`.d.ts`) to include the module declaration. You should be able to save the file anywhere in your project directory.

**Comment by Byron-TW** [comment]
This works, thanks!

**Comment by mboudreau** [comment]
I'll get to this today chaps.

**Comment by mboudreau** [comment]
@samuelmaddock @Byron-TW What version of TS are you using?

**Comment by mboudreau** [comment]
pact-node 6.20.1 is going out as we speak with the fixes (removing @types/bunyan).  Please update to this version and let me know if this works for you.  Cheers.
