### ISSUE TITLE
Improper Error Handling in pacts.rb

### ISSUE THREAD

**Issue by Bmahecha123** [pact-foundation/pact-node#117]
Version: "@pact-foundation/pact-node": "^6.19.11"

Hello, 

When I publish my pacts I am getting a JSON parsing error from the pact_broker ruby client: 
Could not publish pact:
`Error making request - JSON::ParserError A JSON text must at least contain two octets! /node_modules/@pact-foundation/pact-node/standalone/darwin-1.54.4/lib/vendor/ruby/2.2.0/gems/pact_broker-client-1.16.1/lib/pact_broker/client/pacts.rb:21:in block in publish', attempt1 of 3`
    

After digging into where this error is coming from I see it's in this line:
`handle_response(response) do
          latest_link = find_latest_link JSON.parse(response.body)`
I suspect that the body of the response is not in proper JSON format which is causing the errors to show up in my log. Just wanted to bring this to your attention. Once I wrap up this project and if I have time I'll look into getting a fix out for this.
Thank you for your time!

**Comment by Bmahecha123** [comment]
The more I was looking; I see that our in-house pact-broker is returning a string.

**Comment by mefellows** [comment]
Is it something you've done differently (e.g. proxy in front of it) or something in the broker?
