### ISSUE TITLE
Publisher issues

### ISSUE THREAD

**Issue by tarciosaraiva** [pact-foundation/pact-node#12]
I pulled the code to try and submit a fix but the tests keep failing - even on a clean clone - so I decided to write an issue here.

#### Issue 1
Under `publisher.js` on line 99 it uses `urlJoin` to create a URL to PUT to pact-broker. The issue here is related to `data.provider` and `data.consumer` which are both objects. You have to retrieve the actual name by using `data.provider.name` and `data.consumer.name` otherwise the URL built will look like

```
/pacts/provider/[Object%20object]/consumer/[Object%20object]/version/2.0
```

#### Issue 2
When there's a failure there's no way to know what happened. On `publisher.js` line 114 pass back the response object when the promise is rejected.

Thanks

**Comment by mboudreau** [comment]
@mefellows is this related to the change you did/deployed this morning?

**Comment by mefellows** [comment]
Looks like it, but not 100% (off the top of my head). There is a unit test associated with it but it's clearly insufficient. I'll investigate this evening if I can.

**Comment by tarciosaraiva** [comment]
Sorry to be a pain but there's only issue addressed on that commit

**Comment by mefellows** [comment]
Issue 1, do you mean?

**Comment by tarciosaraiva** [comment]
Yup

**Comment by mefellows** [comment]
All good, WIP mate :)

**Comment by tarciosaraiva** [comment]
@mefellows @mboudreau somehow version 4.4.3 didn't get published. Can someone act on it? I have a project here needing this change.

**Comment by mboudreau** [comment]
@tarciosaraiva The fix branch is building.  Waiting to go green before merging and deploying the latest.  Keep your pants on ;)

**Comment by tarciosaraiva** [comment]
I think this is good now. Cheers

**Comment by mefellows** [comment]
👍
