### ISSUE TITLE
pact-node throws promise rejection errors

### ISSUE THREAD

**Issue by TimothyJones** [pact-foundation/pact-node#132]
## Software versions

-   **OS**: Mac OSX 10.13.6
-   **Library version**: `@pact-foundation/pact-node@6.20.0`
-   **Node Version**: `v8.11.0`

## Expected behaviour

Using pact-node shouldn't affect the behaviour of unhandled promise rejections.

## Actual behaviour

When `pact-node` is included in a project, any unhandled promise rejections result in the following error:

```
/Users/work/office/pact/example/node_modules/@pact-foundation/pact-node/standalone/install.js:263
    throw new Error(chalk.red("Unhandled Promise Rejection: " + e));
    ^

Error: Unhandled Promise Rejection: Boom
    at process.<anonymous> (/Users/work/office/pact/example/node_modules/@pact-foundation/pact-node/standalone/install.js:263:11)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

This is a problem, because it prevents the development of APIs that return rejecting promises, and also it is swallowing any supporting information about where the rejection came from.

It's especially a problem if the test setup script `require`s pact, as then any unhandled rejections anywhere in the code will fail.

## Steps to reproduce

Clone this repository: 

https://github.com/TimothyJones/pact-node-rejection-issue

Then:

```
npm install && npm run test
```

## Relevant log files

None, but the error comes from this line:

https://github.com/pact-foundation/pact-node/blob/master/standalone/install.ts#L309

I'm not sure why the handler exists - can anyone shed any light?

**Comment by mlopezluque** [comment]
I've also run into this issue, any news on if the handler is needed or not?

**Comment by jonheslop** [comment]
Also experiencing this issue, we noticed while updating to `@pact-foundation/pact-node@6.20.0` from `@pact-foundation/pact-node@6.16.4` because of this security vulnerability https://www.npmjs.com/advisories/720.

**Comment by mefellows** [comment]
@TimothyJones I'm not sure your example properly highlights the issue, although I've seen first hand what you're describing.

If I comment out the Pact require in your test, it still doesn't pass as expected (instead complaining of `TypeError: Cannot read property 'toEqual' of undefined`). If I modify your code to look more like the Jest [documentation example](https://jestjs.io/docs/en/expect#rejects) it passes no matter if pact is there or not:

```js
const example = require("./index.js");
const pact = require("@pact-foundation/pact");

describe("A simple example", () => {
  it("Should not explode", () => {
    return expect(example()).rejects.toThrow("Boom");
  });
});
```

(Changing the expectation in the `toThrow` makes the test fail for the reasons expected).

I'll see if I can chase this down further.

**Comment by mboudreau** [comment]
Ah, this was added because the original idea is to show if the binaries aren't being loaded properly to the user, but I now see that I added it globally and haven't removed it from the process after the fact.  I'll see if I can do something about this.

**Comment by mefellows** [comment]
Thanks for fixing Michel!
