### ISSUE TITLE
TRACKING SHOULD BE OPT-IN

### ISSUE THREAD

**Issue by chris-fran** [pact-foundation/pact-node#142]
I just realized this library [tracks you by default](https://github.com/pact-foundation/pact-node/blob/master/README.md#do-not-track). This is not OK **and I am very disappointed**, specially since it's not documented in the readme of the MAIN library which is https://github.com/pact-foundation/pact-js.

>To respect your privacy, anyone can turn it off by simply adding a 'do not track' flag within their package.json file:

The fact that you add this line doesn't respect my privacy any more because I didn't know this was a thing in the first place. 

Furthermore, I'm not even sure this library complies with GDPR as I remember something where they mention that to collect user data you must explicitly ask them to opt-in to it and must NOT opt-in by default. Here's [the link](https://www.gdpreu.org/the-regulation/key-concepts/consent/), search for the subtitle "Clear Affirmative [Action]"

**Comment by mboudreau** [comment]
We're responding here mostly: https://github.com/pact-foundation/pact-js/issues/272

**Comment by mboudreau** [comment]
Closing this as we've updated our documentation on the pact-js and clarified that we are only tracking downloads of the binary only, no personally identifiable information is stored, hence we're not in breach of GDPR or any other privacy related laws.
