### ISSUE TITLE
Can I deploy fails incorrectly

### ISSUE THREAD

**Issue by lazytesting** [pact-foundation/pact-node#153]
## Software versions

-   **OS**: Windows 10
-   **Library version**: 8.1.2
-   **Node Version**: 11.6.0

## Expected behaviour

if all verifications are succesful the exit code should be 0

## Actual behaviour

exit code is != 0

## Steps to reproduce

Run can I deploy against the broker (with all verifying successful) and run pact.canDeploy(opt)

## Relevant log files

   Computer says yes \o/

    CONSUMER               | C.VERSION | PROVIDER          | P.VERSION  | SUCCESS?
    -----------------------|-----------|-------------------|------------|---------
    import-status-frontend | 2.1.1     | acc-mgt           | 0.0.0      | true
    import-status-frontend | 2.1.1     | import-status-api | 0-SNAPSHOT | true
    import-status-frontend | 2.1.1     | security-api      | 0.0.0      | true

    All required verification results are published and successful

> but still exit code !=

## solution

The current validation is:
 var success = /All verification results are published and successful/igm.exec(o);

this should be:
var success = /All required verification results are published and successful/igm.exec(o);

But this might still be a bit fragile solution, let me know if you want me to do a PR for this,

**Comment by mboudreau** [comment]
Let me have a look, but my guess is that this is the underlying pact binary
that might be faulty. I'll have a gander tomorrow.

**Comment by TimothyJones** [comment]
What is the value of opt when you’re seeing this behaviour?

**Comment by lazytesting** [comment]
I'm using:
```
const opts = {
    pactFilesOrDirs: [path.resolve(process.cwd(), 'pacts')],
    pactBroker: 'https://xxx.pact.dius.com.au',
    pactBrokerUsername: process.env.PACT_USER,//set the pact broker username as a environment variable
    pactBrokerPassword: process.env.PACT_PASS,//set the pact broker password as a environment variable
    participant: 'import-status-frontend',
    participantVersion: '2.1.1'
};
```

**Comment by TimothyJones** [comment]
Apologies, somehow I didn’t see the solution part of your original post. Yes, a PR would be very welcome, and I agree we should eventually change it to something less brittle.

T

**Comment by mefellows** [comment]
Thanks @lazytesting, version `8.3.2` should be out soon with your fix - much thanks.
