### ISSUE TITLE
upgrade to latest caporal version to avoid lodash vuln

### ISSUE THREAD

**Issue by YOU54F** [pact-foundation/pact-node#159]
Hey, can we upgrade the version of Caporal to avoid a vulnerability in lodash.merge
```
• @pact-foundation/pact:8.2.2
        └─ @pact-foundation/pact-node:8.2.0
              └─ caporal:1.1.0
                    └─ lodash.merge:4.6.1

```

Resolved in PR https://github.com/mattallty/Caporal.js/pull/144

and released in `v1.2.0` https://github.com/mattallty/Caporal.js/releases/tag/v1.2.0

**Comment by TimothyJones** [comment]
Fixed, thanks for the heads up.

**Comment by TimothyJones** [comment]
8.3.1 is building now with this fix.
