### ISSUE TITLE
Publisher fails when broker returns 201 response

### ISSUE THREAD

**Issue by jfnavin** [pact-foundation/pact-node#16]
In v4.4.3 the Publisher will fail if the Pact broker returns a 201 response.

See `publisher.js:132` - the response is being explicitly checked for a 200 even though the broker can return a 201 CREATED response.

**Comment by mefellows** [comment]
Nice pickup, will sort this one out asap.

**Comment by mboudreau** [comment]
good catch :)

**Comment by mefellows** [comment]
Just awaiting Travis CI build to publish: https://travis-ci.org/pact-foundation/pact-node/builds/141193258. OSX builds are broken today which appear to be slowing down all builds.

**Comment by jfnavin** [comment]
Awesome. Cheers!

**Comment by mefellows** [comment]
Build still struggling on at least one OSX [agent](https://www.npmjs.com/package/@pact-foundation/pact-node) - but it has published to NPM and should be sorted now. Thanks for raising!
