### ISSUE TITLE
Please update standalone to 1.69.0

### ISSUE THREAD

**Issue by rafaroca** [pact-foundation/pact-node#165]
Hi,
please update the standalone version to 1.69.0. 
This version includes the pact-broker-client 1.19.0 which contains a fix for passing the broker token via command line.

Beth pointed out that the issue I opened was fixed but needs the standalone to be updated: https://github.com/pact-foundation/pact_broker-client/issues/50

**Comment by TimothyJones** [comment]
Thanks for the heads up! I'm publishing pact-node 8.6.1 with this fix now.

**Comment by rafaroca** [comment]
Sorry to bother again. I cannot see the 8.6.1 release published. It would be great if you could publish the new version as a release. Thanks!

**Comment by mefellows** [comment]
`8.6.2` is on its way now (see tagged build: https://travis-ci.org/pact-foundation/pact-node/builds/553979034)

**Comment by TimothyJones** [comment]
Apologies, looks like I forgot part of the release process.
