### ISSUE TITLE
Update referenced version of caporal

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [pact-foundation/pact-node#168]
This library explicitly references version `1.2.0` of `caporal`.  That version in turn explicitly references a version of `lodash` which contains security vulnerabilities.  

I've created https://github.com/mattallty/Caporal.js/issues/153 and https://github.com/mattallty/Caporal.js/pull/154 to hopefully address that soon.

Once that's released, I'm happy to create a pull request referencing the updated version of `caporal`, but wanted to go ahead and create an issue to make you aware.

**Comment by TimothyJones** [comment]
Thanks @Blackbaud-BobbyEarl ! Feel free to open a PR when you are ready.

We really appreciate this level of commitment to a fix!

**Comment by TimothyJones** [comment]
Also, I've just realised that #167 removes the dependency on Caporal (the PR removes the node-based CLI now that we have binstubs, which simplifies some other issues). That would be another path to a fix.

**Comment by Blackbaud-BobbyEarl** [comment]
Thanks for the update @TimothyJones.  Personally, I have no preference on which technique you choose, just hoping to get rid of the GitHub security alert.  :-)

**Comment by TimothyJones** [comment]
Version `9.0.0` is out with this fix.
