### ISSUE TITLE
Dev chore: replace tslint with eslint

### ISSUE THREAD

**Issue by TimothyJones** [pact-foundation/pact-node#176]
This project uses [ts-lint](https://github.com/palantir/tslint), which will be deprecated "some time in 2019" (see [here for their roadmap](https://github.com/palantir/tslint/issues/4534)).

Their recommendation is to migrate to eslint, which now has typescript support. 

I'm making this ticket to remind us to make the switch.

While we're there, we could also enable linting during the build pipeline - there's a script in package.json, but I don't believe it currently runs.

**Comment by flagoon** [comment]
Hey, if it's OK, I would like to take this issue.

**Comment by TimothyJones** [comment]
Please feel free!

**Comment by flagoon** [comment]
I have a question. When I replaced tslint with eslint and use recommended eslint settings, and it's throws some errors/warnings. Should I fix those errors, or ignore them in eslintrc?
Errors I'm talking about:
@typescript-eslint/ban-ts-ignore
@typescript-eslint/no-use-before-define
@typescript-eslint/camelcase
@typescript-eslint/no-inferrable-types
indent

WARNINGS:
@typescript-eslint/no-explicit-any
@typescript-eslint/explicit-function-return-type
@typescript-eslint/no-unused-vars

I suggest two solutions
1. fix errors/warning and include them in this PR
2. set those errors to ignore in eslintrc, merge, and I or someone else could fix those errors in another PR

How should we proceed?

**Comment by TimothyJones** [comment]
I reckon fix the errors and include them in the PR is probably the best option. Would you agree?

**Comment by flagoon** [comment]
Unfortunatelly I forgot to add the reviewer, and right now I don't know how to do this at github. Here's PR: https://github.com/pact-foundation/pact-node/pull/187

**Comment by TimothyJones** [comment]
Many thanks for the PR, @flagoon!
