### ISSUE TITLE
Resolve with output on canDeploy success

### ISSUE THREAD

**Issue by kuangp** [pact-foundation/pact-node#180]
Would it be possible to resolve with the resulting output on a successful `canDeploy` call here: https://github.com/pact-foundation/pact-node/blob/master/src/can-deploy.ts#L111

This would allow the consumer to leverage the metadata returned by `can-i-deploy` that lists all known integrations and associated versions and also make it consistent with the error scenario which does return this information.

I would be happy to throw up a PR if this is approved

**Comment by TimothyJones** [comment]
A PR for this would be very welcome!  The underlying binary supports JSON output (`--output=json`), so you don't even need to write a parser.

I'm curious - what's your use case is for calling `canDeploy` programatically?

Also, if you're calling it programatically, you might have an opinion on https://github.com/pact-foundation/pact-node/pull/173

**Comment by mefellows** [comment]
PR welcome - makes complete sense to me!

**Comment by kuangp** [comment]
@TimothyJones I'm calling `canDeploy` programmatically in a github app I'm developing to decorate PRs on my projects with pact verification results. This all requires being able to extract the output results of `canDeploy`

**Comment by kuangp** [comment]
@TimothyJones @mefellows I put up a PR for this change. Can you guys take a look when you get a chance please? Thanks.
