### ISSUE TITLE
Pact client doesn't send DELETE requests with body correctly

### ISSUE THREAD

**Issue by jnazander** [pact-foundation/pact-node#183]
## Software versions

-   **OS**: Windows 10
-   **Library version**: 9.0.4
-   **Node Version**: 10.15.3

## Expected behaviour

Pact mock client during pact provider tests should send HTTP DELETE requests with HTTP body correctly.

## Actual behaviour

It doesn't send HTTP DELETE requests correctly.

I'm using Node.js with Express framework as the server, and I'm running pact provider tests / pact verifications. One of the pact interactions is a DELETE request that has a request body ([The spec](http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html) does not forbid it). All other requests go through fine, but the delete request seemingly makes the server freeze and not return anything until the timeout, at which it resets the HTTP connection (see the pact provider log attached).

Upon further investigation with Wireshark I found out the underlying problem: the pact mock client doesn't even send all of the TCP packets that make up the HTTP DELETE request - it stops short of sending the body. This makes the server wait for the remaining packet, which never comes, thus hanging the test until it times out.

![image](https://user-images.githubusercontent.com/4726607/65143985-f5d8a200-da1e-11e9-94a2-85af95d38e5b.png)

Interestingly, it does send `Content-Length: 15` in the first packet, indicating that there will be a body in the following packet(s), but it never sends it.

## Steps to reproduce

Try to verify a pact with the following interaction:

```
{
      "description": "A DELETE request to delete one reminder",
      "providerState": "User user1@example.com exists with 2 smart reminders",
      "request": {
        "method": "DELETE",
        "path": "/api/users/22/schedule",
        "headers": {
          "Content-Type": "application/json",
        },
        "body": {
          "items": [
            100
          ]
        }
      },
      "response": {
        "status": 204,
        "headers": {
        }
      }
    }
```
(or any pact that has a HTTP DELETE method with a request body).

## Relevant log files

Log file generated by pact provider test attached.
[pact-provider.log](https://github.com/pact-foundation/pact-node/files/3625986/pact-provider.log)

**Comment by jnazander** [comment]
Also, I understand that it's not the Pact library's fault, but one of the underlying HTTP client. But I'm having a hard time figuring out which one. Is it `request`, `@types/request` or some other?

**Comment by TimothyJones** [comment]
`pact-node` wraps the pact-standalone ruby implementation, so I suspect that is the culprit (a quick stackoverflow search [suggests](https://stackoverflow.com/questions/14704885/how-to-send-delete-request-with-body-using-ruby-gem) that many ruby http clients don't support delete with bodies).

You might want to open an issue on [pact-ruby](https://github.com/pact-foundation/pact-ruby). (@bethesque - is that the right place? I'm surprised we haven't hit this before).

**Comment by TimothyJones** [comment]
@jnazander can you confirm that this issue exists if you call `pact-provider-verifier` directly?

```
$ node_modules/.bin/pact-provider-verifier
```

you can see the options with 
```
$ node_modules/.bin/pact-provider-verifier --help
```

**Comment by jnazander** [comment]
@TimothyJones 
I checked with `pact-provider-verifier` directly and it does the same thing, sending the first packet, waiting a few minutes and then timing out with EOFError:

```
Failures:

  1) Verifying a pact between mobile-app and app-api-delete-test Given User user1@example.com exists with 2 smart reminders A DELETE request to delete one reminder with DELETE /api/users/22/schedule returns a response which has status code 204
     Failure/Error: replay_interaction interaction, options[:request_customizer]

     EOFError:
       end of file reached


1 interaction, 1 failure

Failed interactions:

* A delete request to delete one reminder given User user1@example.com exists with 2 smart reminders
```

**Comment by jnazander** [comment]
Created an issue in `pact-ruby` - https://github.com/pact-foundation/pact-ruby/issues/198

**Comment by TimothyJones** [comment]
Thanks. That means the issue definitely lies with the ruby implementation.

I'm not sure whether the right place to raise it is [pact-provider-verifier](https://github.com/pact-foundation/pact-provider-verifier/issues) or [pact-ruby](https://github.com/pact-foundation/pact-ruby/issues). Can you open an issue over on one of those? 

I'll leave this issue open because we'll need to upgrade the pact-standalone version once it is fixed.

**Comment by TimothyJones** [comment]
Nice, our messages crossed. Thanks for being so proactive!

**Comment by TimothyJones** [comment]
Releasing v10.2.4, which should have a fixed version of pact-standalone. Let us know how you go

**Comment by bethesque** [comment]
Someone else had this issue recently, and I told them I didn't think it could be fixed. Will have to do a search of all the issues and try and track it down.
