### ISSUE TITLE
willRespondWith headers are filtered

### ISSUE THREAD

**Issue by inkhsutesou** [pact-foundation/pact-node#185]
## Software versions

-   **MAC OS**
-   **8.1.2/74293**
-   **v10.12.0**

## Expected behaviour
```
willRespondWith: {
  status: 503,
  headers: {
    'Retry-After': '1000',
    'Content-Type': 'application/json'
  }
}
```
should have an `error.response.headers` with ..

```
{
    'Retry-After': '1000',
    'Content-Type': 'application/json'
}
```

## Actual behaviour
Returns with:
```
{
    'Content-Type': 'application/json'
}
```

Can anyone tell me why the headers would be filtering ?  I have tried this across several teams at my company and they all run into this same issue.  Checking to see if this is an issue with pact-node.  Thank you.

**Comment by mefellows** [comment]
Closing, see pact js issue.
