### ISSUE TITLE
Question: Can I use `can-i-deploy` without username and password?

### ISSUE THREAD

**Issue by yosevukilonzo** [pact-foundation/pact-node#191]
## Software versions

-   **OS**: e.g. Mac OSX 10.14.6
-   **Library version**: e.g. 9.0.6
-   **Node Version**: 10.4.1

## Expected behaviour

I can call `can-i-deploy` without basic auth username and password for a pact broker that doesn't use basic auth.

## Actual behaviour

I can't call `can-i-deploy` without basic auth username and password for a pact broker that doesn't use basic auth.

## Steps to reproduce

Hello! This is more of a question. I'm not sure if it is expected or not.

I am able to run the command successfully with a pact broker that has basic auth set up e.g.
`./node_modules/.bin/pact-broker can-i-deploy --pacticipant "Banana Service" --broker-base-url http://pract-broker-with-basic-auth --latest --broker-username dXfltyFMgNOFZAxr8io9wJ37iUpY42M --broker-password O5AIZWxelWbLvqMd8PkAVycBJh2Psyg1`

But it fails when I run the command with a pact broker that doesn't have basic auth e.g.

`./node_modules/.bin/pact-broker can-i-deploy --pacticipant "Banana Service" --broker-base-url http://pact-broker-with-no-basic-auth --latest`

## Relevant log files

Please ensure you set logging to `DEBUG` and attach any relevant log files here (or link from a gist).

**Comment by mefellows** [comment]
You should definitely be able to call `can-i-deploy` on a broker without authentication. Are you able to provide more information on the error itself?

**Comment by yosevukilonzo** [comment]
Yes, I need to be on a VPN to access that URL. Could that be related?

Currently seeing this:

```
Error making request - Net::ReadTimeout Net::ReadTimeout /path/to/@pact-foundation/pact-node/standalone/darwin-1.70.2/lib/vendor/ruby/2.2.0/gems/pact_broker-client-1.20.0/lib/pact_broker/client/matrix.rb:13:in `get', attempt 1 of 3
```

**Comment by mefellows** [comment]
I would say so, assuming that you're not on the VPN. How would you expect it to behave?

**Comment by yosevukilonzo** [comment]
I don't think my previous message was clear. I was on VPN and the command did work with a pact broker that has authentication, so my VPN comment may not be relevant, sorry.

**Comment by mefellows** [comment]
No worries, thanks. A read timeout suggests your machine is not able to reach the target host - so it seems more network related than anything. Can you connect to the pact broker via telnet or some other CLI utility to demonstrate there is connectivity?

I'm currently not sure how to progress this issue. If you can demonstrate this issue with a local pact broker (using Docker or something) we can look into it further. Otherwise I'll close this off until we can reproduce.

**Comment by yosevukilonzo** [comment]
Sounds good, I'll close it for now and see if I can reproduce it locally. Thank you.

**Comment by mefellows** [comment]
No probs, thanks.
