### ISSUE TITLE
Unable to start pact on windows

### ISSUE THREAD

**Issue by antoineVgs** [pact-foundation/pact-node#197]
## Software versions

-   **OS**:  Windows 10
-   **Library version**: 9.2.1
-   **Node Version**: 10.16.0

## Expected behaviour

pact process is starting normaly

## Actual behaviour

Pact is not starting when the folder length is > than  80 characters.
I saw the readme but changing the registry value HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled to 1 has no effect.

## Steps to reproduce

Provide a repository, gist or reproducible code snippet so that we can test the problem.

Consider forking the project and modifying the [E2E test](https://github.com/pact-foundation/pact-ruby-standalone-e2e-example)

## Relevant log files

Please ensure you set logging to `DEBUG` and attach any relevant log files here (or link from a gist).
    Pact Binary Error: D:/loooooooooooooooooooooooooooooooooooooooongpaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaath/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/pact-mock_
service-3.1.1/lib/pact/mock_service/app.rb:5:in `require': cannot load such file -- pact/consumer/mock_service/cors_origin_header_middleware (LoadError)
        from D:/loooooooooooooooooooooooooooooooooooooooongpaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaath/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.
1.1/lib/pact/mock_service/app.rb:5:in `<top (required)>'
        from D:/loooooooooooooooooooooooooooooooooooooooongpaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaath/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.
1.1/lib/pact/mock_service/run.rb:2:in `require'
        from D:/loooooooooooooooooooooooooooooooooooooooongpaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaath/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.
1.1/lib/pact/mock_service/run.rb:2:in `<top (required)>'
        from D:/loooooooooooooooooooooooooooooooooooooooongpaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaath/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.
1.1/lib/pact/mock_service/cli.rb:33:in `require'
        from D:/loooooooooooooooooooooooooooooooooooooooongpaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaath/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/pact-mock_service-3.
1.1/lib/pact/mock_service/cli.rb:33:in `service'
        from D:/loooooooooooooooooooooooooooooooooooooooongpaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaath/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor
/command.rb:27:in `run'
        from D:/loooooooooooooooooooooooooooooooooooooooongpaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaath/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor
/invocation.rb:126:in `invoke_command'
        from D:/loooooooooooooooooooooooooooooooooooooooongpaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaath/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor
.rb:387:in `dispatch'
        from D:/loooooooooooooooooooooooooooooooooooooooongpaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaath/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor
/base.rb:466:in `start'
        from D:/loooooooooooooooooooooooooooooooooooooooongpaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaath/node_modules/@pact-foundation/pact-node/standalone/win32-1.70.2/lib/app/pact-mock-service.rb:15:in `<main>'
    
[2019-10-29T08:27:23.185Z]  WARN: pact-node@9.0.7/7724 on PAVER02: Pact exited with code 1.
[2019-10-29T08:27:23.185Z]  INFO: pact-node@9.0.7/7724 on PAVER02: Removing Pact with PID: 9924

**Comment by mefellows** [comment]
There are already a few issues that document this scenario (e.g. #101) . Unfortunately until we release a major overhaul of the library integrating our new Rust engine, we can't do anything about it.
