### ISSUE TITLE
Can't retrieve pacts from broker behind reverse proxy

### ISSUE THREAD

**Issue by mcclenney** [pact-foundation/pact-node#198]
## Software versions

-   **OS**: Mac OSX 10.14.6
-   **Library version**: 9.0.6
-   **Node Version**: v10.16.2

## Expected behaviour

I'm expecting to be able to publish and retrieve pacts from a broker that is behind a reverse proxy. I have a self-signed certificate that is used to authenticate with the broker.

Initially, I could not publish to the broker. I found this issue: https://github.com/pact-foundation/pact-node/issues/93 and saw that I needed to use the env variable SSL_CERT_FILE. So I set that variable and then was able to publish. But, I still failed to retrieve pacts from the broker with error "certificate verify failed". It appears that problem was referenced in https://github.com/pact-foundation/pact-node/issues/93 as well, but never resolved.

## Actual behaviour

Failure to retrieve pacts from broker, even when SSL_CERT_FILE environment variable is pointing to the correct PEM file.

## Steps to reproduce

The publishing works because SSL_CERT_FILE is passed to the httparty library used to publish files, line 47 here: https://github.com/pact-foundation/pact_broker-client/blob/master/lib/pact_broker/client/base_client.rb

I can see that SSL_CERT_FILE is set in the ruby code used by pact-node, but it doesn't appear to be passed to the net/http library. So, I explicitly set the net/http "ca_file" instance variable to point to the SSL_CERT_FILE env variable.

I added two lines below line 56 in file https://github.com/pact-foundation/pact-ruby/blob/master/lib/pact/hal/http_client.rb

```
http.ca_file = ENV["SSL_CERT_FILE"]
http.ca_path = ENV["SSL_CERT_DIR"]
http.start do |http|
```

Also, I had to make a change to line 84 in file https://github.com/pact-foundation/pact-support/blob/master/lib/pact/consumer_contract/pact_file.rb. Had to explicitly set ca_file to ENV["SSL_CERT_FILE"] here as well:

```
Net::HTTP.start(uri.host, uri.port, :ENV, use_ssl: uri.scheme == 'https', ca_file: ENV["SSL_CERT_FILE"], ca_path: ENV["SSL_CERT_DIR"]) do |http|
```

I am new to Ruby and don't know if those fixes are ideal, but it's how I got the pact retrieval for provider verification working, and no more "certificate verify failed" error.

Let me know if I am missing something that would make this work without those code changes.

**Comment by mefellows** [comment]
Including Beth in the conversation, I'll investigate later in the week.

**Comment by bethesque** [comment]
I've released 1.79.0 of the standalone with these changes. Can you please update @mefellows?

**Comment by bethesque** [comment]
Corine is keen to have this fix too!

**Comment by mefellows** [comment]
Sorry, I ran the release script but didn't push - `v10.3.0` is on the way now...

**Comment by mefellows** [comment]
Gah, some travis [bug](https://travis-ci.community/t/missing-api-key-when-deploying-to-github-releases/5761/13) stopped the release. Added a patch, and now `10.3.1` is out (https://www.npmjs.com/package/@pact-foundation/pact-node).
