### ISSUE TITLE
Does pact-node support asynchronous contract testing?

### ISSUE THREAD

**Issue by basickarl** [pact-foundation/pact-node#205]
Does pact-node support asynchronous contract testing or must I use the pact-js module for this? I read the README and it didn't mention anywhere that it was for synchronous or asynchronous communication.

**Comment by mefellows** [comment]
No, it does not, use Pact JS instead (I've added more detail to https://github.com/pact-foundation/pact-js/issues/408).

**Comment by TimothyJones** [comment]
It’s better to think of pact-node as “pact-core”. It’s called node for legacy reasons- id like to rename it some time.

**Comment by mefellows** [comment]
As per Pact Js, I've just added a table to the top of the repo. Let's see how it goes and if it helps clear things up.
