### ISSUE TITLE
Postinstall seems to ignore strict-ssl=false

### ISSUE THREAD

**Issue by alongotban** [pact-foundation/pact-node#211]
We are using pact behind a corporate firewall. In view of https://github.com/pact-foundation/pact-node/issues/88 we have the following pact-related entries in our package.json:

```
  "config": {
    "pact_binary_location": "https://artifactory.ourcompany.com.au/artifactory/pact-github-repo/download/v1.81.0/"
  },
...
  "devDependencies": {
    "@pact-foundation/pact": "^9.6.0",
...
```
Our .npmrc contains
```
strict-ssl=false
cafile=/usr/local/ourcompany/certificates/ourcompany-proxy-internal.cer
```
which works for all packages - except for pact-foundation. We get:
```
Installing Pact Standalone Binary for darwin.
Downloading Pact Standalone Binary v1.73.0 for platform darwin from https://artifactory.ourcompany.com.au/artifactory/pact-github-repo/download/v1.81.0/pact-1.73.0-osx.tar.gz
Error: Error while installing binary: Postinstalled Failed Unexpectedly: Error downloading binary from https://artifactory.ourcompany.com.au/artifactory/pact-github-repo/download/v1.81.0/pact-1.73.0-osx.tar.gz: Error: Error while installing binary: Error: self signed certificate in certificate chain
```
We can curl https://artifactory.ourcompany.com.au/artifactory/pact-github-repo/download/v1.81.0/pact-1.73.0-osx.tar.gz, so we know the URL is correct. 

It appears that the postinstall script https://github.com/pact-foundation/pact-node/blob/master/standalone/install.ts does not use the strict-ssl=false setting.

**Comment by mefellows** [comment]
Thanks for the report. I've pushed up a small change now, we'll get this out in the next release.

**Comment by alongotban** [comment]
Nice, thanks very much @mefellows. How can I find out when the next release will be coming out ? (This is blocking us from using Pact, unfortunately).

**Comment by mefellows** [comment]
No worries. I just need another maintainer to review and sign off, and then we'll release. Usually, just a few days (so mid next week I'd say).

**Comment by alongotban** [comment]
Great news @mefellows . I also noticed that I have to specify the version ${PACT_STANDALONE_VERSION} as part of the pact_binary_location:

    "pact_binary_location": "https://artifactory.ourcompany.com.au/artifactory/pact-github-repo/download/v1.81.0/"

where as this could be done by the function createConfig() in install.ts. Then the binary location would not have to be updated when new version are available. Would you like me to create a separate issue/request for this ?

**Comment by mefellows** [comment]
A separate issue would be great, thanks.

This is a fairly straightforward thing - we need to honour a standard npm setting.

In the other case, I think we'll need to discuss the pros/cons and interface for it.
