### ISSUE TITLE
having trouble verifying pacts from broker

### ISSUE THREAD

**Issue by travi** [pact-foundation/pact-node#22]
when running `verifyPacts` with `pactUrls` pointing to local files, it is successfully doing verification of the pact. however, as soon as i try to change the url to point to a pact on my remote broker (https and using basic auth), i get the following error:

```
[Error: /bin/sh: <part of the password>: command not found
/bin/sh: <a different part of the password>: command not found
/Users/admin/development/travi.org/api/node_modules/@pact-foundation/pact-provider-verifier-darwin/lib/app/lib/pact/provider_verifier/app.rb:32:in `get_pact_consumer_name': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/admin/development/travi.org/api/node_modules/@pact-foundation/pact-provider-verifier-darwin/lib/app/lib/pact/provider_verifier/app.rb:55:in `block in verify_pacts'
	from /Users/admin/development/travi.org/api/node_modules/@pact-foundation/pact-provider-verifier-darwin/lib/app/lib/pact/provider_verifier/app.rb:54:in `collect'
	from /Users/admin/development/travi.org/api/node_modules/@pact-foundation/pact-provider-verifier-darwin/lib/app/lib/pact/provider_verifier/app.rb:54:in `verify_pacts'
	from /Users/admin/development/travi.org/api/node_modules/@pact-foundation/pact-provider-verifier-darwin/lib/app/lib/pact/provider_verifier/cli.rb:18:in `verify'
	from /Users/admin/development/travi.org/api/node_modules/@pact-foundation/pact-provider-verifier-darwin/lib/vendor/ruby/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/admin/development/travi.org/api/node_modules/@pact-foundation/pact-provider-verifier-darwin/lib/vendor/ruby/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/admin/development/travi.org/api/node_modules/@pact-foundation/pact-provider-verifier-darwin/lib/vendor/ruby/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/admin/development/travi.org/api/node_modules/@pact-foundation/pact-provider-verifier-darwin/lib/vendor/ruby/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/admin/development/travi.org/api/node_modules/@pact-foundation/pact-provider-verifier-darwin/lib/app/pact-provider-verifier.rb:3:in `<main>'
]
```

note that the pact that i was using locally was a file fetched directly from the same url and credentials using postman.

i would expect that if it were failing to fetch from the broker, that i would get an error related to the fetch, but i'm not sure how to get more information about the context of the error. i did notice that parts of my password for the broker show up in the error (the minor edits in the output above). they seem to be split after `&` characters. if this is the case, i'm surprised that i don't get a "failed to auth" error before it tries to parse for a consumer name.

could you provide some guidance about how to dig deeper? is there a way to put the ruby portion into a debug mode? if this issue is that special characters need to be escaped, i'm not sure what the sequence would need to be here since i am passing the string as an option to `verifyPacts`. could it be updated to do the necessary escaping automatically?

**Comment by travi** [comment]
Also, that same password string is working fine for calls to `publishPacts`

**Comment by travi** [comment]
i've tried using `\` and `\\` in an attempt to escape the characters that appear to be (maybe?) causing splitting as well as url encoding the password. i'm not sure what other escaping methods would be more appropriate here, or if that is even what is causing the problem for sure.

any help in how to debug this a bit further would be greatly appreciated

**Comment by mboudreau** [comment]
@mefellows Can you shine some light as to why the provider-verifier is doing this?

@travi can you give us a working example of how you create this issue?

**Comment by travi** [comment]
my script can be found [here](https://github.com/travi/travi-api/blob/94afa10a3c028ebb96f7e659ddf332d3240a148e/scripts/pact-verification.js). it obviously does not contain the offending password, but i can at least share that the password does include the special characters `&`, `^`, `*`, and `@`. I still see the `*` and `^` in the output, but the segments that are in the input are the portions that follow the `&`s (the `@` happens to be in the first portion of the password, before the first `&`).

<details>
    <summary>My pact</summary>
```json
{
  "consumer": {
    "name": "travi.org-admin"
  },
  "provider": {
    "name": "travi-api"
  },
  "interactions": [
    {
      "description": "a GET request for the api catalog",
      "request": {
        "method": "get",
        "path": ""
      },
      "response": {
        "status": 200,
        "headers": {},
        "body": {
          "_links": {
            "self": {
              "href": "https://api.travi.org/"
            },
            "rides": {
              "href": "https://api.travi.org/rides"
            },
            "users": {
              "href": "https://api.travi.org/users"
            }
          }
        }
      }
    }
  ],
  "metadata": {
    "pactSpecificationVersion": "2.0.0"
  },
  "createdAt": "2016-03-27T04:22:06+00:00",
  "_links": {
    "self": {
      "title": "Pact",
      "name": "Pact between travi.org-admin (v0.0.1) and travi-api",
      "href": "https://pact-api.travi.org/pacts/provider/travi-api/consumer/travi.org-admin/version/0.0.1"
    },
    "pb:consumer": {
      "title": "Consumer",
      "name": "travi.org-admin",
      "href": "https://pact-api.travi.org/pacticipants/travi.org-admin"
    },
    "pb:provider": {
      "title": "Provider",
      "name": "travi-api",
      "href": "https://pact-api.travi.org/pacticipants/travi-api"
    },
    "pb:latest-pact-version": {
      "title": "Pact",
      "name": "Latest version of this pact",
      "href": "https://pact-api.travi.org/pacts/provider/travi-api/consumer/travi.org-admin/latest"
    },
    "pb:previous-distinct": {
      "title": "Pact",
      "name": "Previous distinct version of this pact",
      "href": "https://pact-api.travi.org/pacts/provider/travi-api/consumer/travi.org-admin/version/0.0.1/previous-distinct"
    },
    "pb:diff-previous-distinct": {
      "title": "Diff",
      "name": "Diff with previous distinct version of this pact",
      "href": "https://pact-api.travi.org/pacts/provider/travi-api/consumer/travi.org-admin/version/0.0.1/diff/previous-distinct"
    },
    "pb:pact-webhooks": {
      "title": "Webhooks for the pact between travi.org-admin and travi-api",
      "href": "https://pact-api.travi.org/webhooks/provider/travi-api/consumer/travi.org-admin"
    },
    "pb:tag-prod-version": {
      "title": "Tag this version as 'production'",
      "href": "https://pact-api.travi.org/pacticipants/travi.org-admin/versions/0.0.1/tags/prod"
    },
    "pb:tag-version": {
      "title": "Tag version",
      "href": "https://pact-api.travi.org/pacticipants/travi.org-admin/versions/0.0.1/tags/{tag}"
    },
    "curies": [
      {
        "name": "pb",
        "href": "https://pact-api.travi.org/doc/{rel}",
        "templated": true
      }
    ]
  }
}
```
</details>

let me know if there are additional details that would be helpful.

**Comment by mefellows** [comment]
Thanks @travi - I'll take a look at this and have created an issue over at the verifier. It's probably just a matter of properly escaping the string in the `pact-provider-verifier` gem.

**Comment by mefellows** [comment]
Update: I've taken a quick look this morning and I am able to supply passwords with these chars to the provider verifier. I currently suspect https://github.com/pact-foundation/pact-node/blob/master/src/verifier.js#L58 is the issue, it should probably be wrapping these arguments in quotes.

**Comment by mboudreau** [comment]
Cool, I'll see if I can fix that and do a release.

**Comment by mefellows** [comment]
I'm half way through a fix from this morning, I'll submit a PR in an hour or 2.

**Comment by travi** [comment]
i can confirm that the change in master does resolve the issue that i was seeing. thank you for the quick resolution. will there be a release that includes the fix cut soon?

**Comment by mboudreau** [comment]
Good to hear. I'll get a release out today.

**Comment by mefellows** [comment]
Awesome news @travi, thanks for checking out the master and testing for us.

**Comment by mboudreau** [comment]
@travi new version released with those changes: 4.5.4.

Please let me know how that goes.  Cheers.

**Comment by mefellows** [comment]
Nice work team!

**Comment by travi** [comment]
Looks good on my end. Thanks again.
