### ISSUE TITLE
Provider verification against https endpoint

### ISSUE THREAD

**Issue by gvijayakumar-16** [pact-foundation/pact-node#221]
## Software versions

-   **OS**: 10.14.3
-   **Library version**: 10.8.0
-   **Node Version**: 10.15.2

## Expected behaviour

Provider verification to run successfully against self signed https endpoint

## Actual behaviour

Throws the error
```
Uncaught Error: write EPROTO 140574248376192:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

      at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
```

## Steps to reproduce

The configuration I am using 
```
let opts = {
            provider: "api",
            providerBaseUrl: "https://my-domain.com",
            pactUrls: [
                path.resolve(
                    process.cwd(),
                    "./pacts/pact-api.json"
                ),
            ],
            validateSSL: false,
            changeOrigin: true,
            providerVersion: "1.0.0"
        }
        return new Verifier(opts).verifyProvider().then(output => {
            console.log("Pact Verification Complete!")
            console.log(output)
        })
```

When I use http:// , I am getting a response with status code 308 (redirect) and the pact verification runs to completion. But when I change to https:// above error is thrown.

**Comment by mefellows** [comment]
Is this issue resolved now?

**Comment by gvijayakumar-16** [comment]
This is being tracked over here
https://github.com/pact-foundation/pact-js/issues/429
