### ISSUE TITLE
Error message when verifying message consumer pact

### ISSUE THREAD

**Issue by thombergs** [pact-foundation/pact-node#228]
I'm trying to create an example for message contracts along the lines of the [examples ](https://github.com/pact-foundation/pact-js/tree/master/examples/messages) in the pact-js repo.

The consumer test is successful, but pact-node does not write the Pact file. The console shows this error message:

```
 ERROR: "pact-message update" was called with arguments ["{\"description\":\"a hero", "created message\",\"contents\":{\"id\":{\"contents\":42,\"json_class\":\"Pact::SomethingLike\"},\"name\":{\"contents\":\"Superman\",\"json_class\":\"Pact::SomethingLike\"},\"superpower\":{\"contents\":\"flying\",\"json_class\":\"Pact::SomethingLike\"},\"universe\":{\"data\":{\"generate\":\"DC\",\"matcher\":{\"json_class\":\"Regexp\",\"o\":0,\"s\":\"^(DC|Marvel)$\"}},\"json_class\":\"Pact::Term\"}},\"metadata\":{\"content-type\":\"application/json\"}}"]
    Usage: "pact-message update MESSAGE_JSON --consumer=CONSUMER --pact-dir=PACT_DIR --provider=PROVIDER"
```

I have pushed the code to github [here](https://github.com/thombergs/code-examples/tree/master/pact/pact-node-messages). The problem can be reproduced by calling `npm run test:consumer`.

Do you have an idea what's wrong with my example? 

The example from the pact-js repo runs fine on my machine (at least after adding a missing `done()`). But I don't see the difference between both examples.

**Comment by TimothyJones** [comment]
This is (finally) fixed in v10.11.2. Sorry it took so long!
