### ISSUE TITLE
Underscores in header keys are changed to hyphens during requests

### ISSUE THREAD

**Issue by andrew-allen** [pact-foundation/pact-node#24]
I have generated an interaction that expects the following request headers:

    "headers": {
        "Accept": "application/json",
        "customer_key": "1",
        "tenant_key": "1"
    }
When attempting to hit the the wrapper server, headers get transformed into a different format. Partial output from the mock-server-integration logs:

    "headers": {
        "Customer-Key": "1",
        "Tenant-Key": "1",
        "Host": "localhost:1234",
        "Accept": "application/json",
        "Connection": "close",
        "Version": "HTTP/1.1"
    }
Is there some way to stop this transformation of custom headers with underscores?

**Comment by mboudreau** [comment]
Hm, using underscores in headers is extremely unusual, probably against the
http spec, hence the conversion.  The issue is not with pact-node however,
but with the underlying pact-mock_service binary.  If you'd want this to be
rectified, you'll have to create a feature request there.

**Comment by mboudreau** [comment]
@andrew-allen Anything else to add?  Did you create an issue on the other project?

**Comment by andrew-allen** [comment]
We ended up going with spinal case header formats, closing this as its not an issue in this project.
