### ISSUE TITLE
The node wrapper should pass the new --sslcert and --sslkey options to server

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [pact-foundation/pact-node#27]
Two new command line options, `--sslcert` and `--sslkey`, were added to the Ruby pact mock service which this library wraps.  These options allow you to specify a particular SSL certificate instead of using one that's generated each time.  This way you can create a certificate, add it to your computer's list of trusted root certificates, and avoid the SSL errors typically thrown by web browsers.  I plan on submitting a PR for this shortly.

https://github.com/bethesque/pact-mock_service/pull/56

**Comment by mboudreau** [comment]
@Blackbaud-PaulCrowder 

Hi,

We've just released version 4.7.0 of pact-node, which has this new functionality.  Please refer to the readme for the usage. 

Please confirm that this is working for you and get back to us so that we can close this issue.

Cheers.

**Comment by Blackbaud-AlexKingman** [comment]
Thanks, @mboudreau 

I'm trying to use the `sslcert` and `sslkey` params that's included in version 4.7.0, but it doesn't seem to be overwriting the cert. I get the same auto-generated cert each time. Also, I noticed that when giving the params bad paths to non-existent files, there doesn't seem to be any errors in the log. Am I doing something wrong?

Thanks.

**Comment by mefellows** [comment]
I've created a [gist](https://gist.github.com/mefellows/1d9d6e76412b9326b4f96dfe7ee7e3c8) to replicate the issue. When I run it, I get a failure indicating it can't find the ssl certificate (or key if I create the file). 

Are you able to modify or create a gist to assist?

FWIW we have a few integration-like [tests](https://github.com/pact-foundation/pact-node/blob/master/src/server.spec.js#L94-L108) that test this behaviour.

**Comment by mboudreau** [comment]
Alex,

We'll try to replicate the issue and squash the bug, but you'll need to
provide a bit more information as to what's outputted, what you're trying
and which OS you're on.

Cheers.

**Comment by Blackbaud-AlexKingman** [comment]
@mefellows @mboudreau Thanks for your quick help! Now that I understand the implementation a bit more, I see that my original question was a bit misguided. The `createServer` method in pact-node does indeed work properly, as your gist shows. However, I'm trying to implement these options from the pact-js library, and I see that the constructor in pact-js doesn't yet handle the `sslcert` and `sslkey` params.

Will those be coming soon to pact-js?

Thanks again!

**Comment by mefellows** [comment]
No worries! It's on my to-do, but I'll try and get that sorted this morning for you. Closing this for now.
