### ISSUE TITLE
Strange issue reading contract file

### ISSUE THREAD

**Issue by jonoc330** [pact-foundation/pact-node#32]
For some reason any time pact node attempts to retrieve a contract file (via http or file system) there is an error reading the contract.

**Error: reading pact at /path/to/json.json**

What I know is:

- I've tried multiple contract files on the file system/http requests to no success. 
- Doing a manual GET request to the HTTP URLs I'm using works fine. 
- Permissions of the contract files on the file system are fine. 
- Happens in both 4.7.0 and 4.8.0 and really only just started happening without any change to my environment. 
- The contracts themselves are valid JSON and look correct as far as structure.
- Looks like the same issue if you skip pact-node and go straight to the verifier.

Not much to go on, but have you seen this before?

**Comment by jonoc330** [comment]
Closing this as I've realised Error: reading pact at is basically a blanket message if there are errors with the provider verification - it's not actually an error "reading" the pact so to speak.

**Comment by mboudreau** [comment]
Hm, we might want to fix that error message then to be more specific.
Please keep this open.
