### ISSUE TITLE
Allow relative paths in pact publish task

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-node#33]
Currently, when passing `pactUrls` to the publish task, the urls need to be absolute. It would be nice to pass in a relative path.

See https://github.com/pact-foundation/pact-js/issues/31 + https://github.com/pact-foundation/pact-node/commit/a5afdb17e2c3ca8acf6c6a2051e7575cc4bcb4b2#commitcomment-21360868 for background.

I suspect part of the complication is relativity to the underlying Ruby process, so we would need to convert to an absolute path under the hood anyway.

**Comment by mboudreau** [comment]
@mefellows I'm looking into this one and thinking of adding something in the pact-util file that checks for paths/urls and then normalizes/resolves them if they're valid.

Currently though, we're a bit "laissez-faire" with the path validation as we do some minute checks on it, but nothing too concrete.  I do agree that we need to have the ability to check relative vs absolute paths, however, should we also accept path shortcuts like `~/`?  

Also, when it comes to URLs, should we accept any protocols, or is it locked down to http(s)?

Trying to figure out the best way to do this as to implement it properly.

**Comment by mefellows** [comment]
I don't see why other protocols could not be supported in the long term, i'm not sure what is currently supported beyond `file://` and `http://`.

However I think we don't allow unix/bash/whatever-specific shortcuts like `~`. I can't think of a situation where it's going to be terrible, but I can see implementation complexity with little value.

WRT other protocols, all that we need is the URL to be resolvable from the local host, and the Pact verifier to support it.

cc: @bethesque who also has some good knowledge around the verifier and might be able to assist.

**Comment by bethesque** [comment]
Why not just pass the paths in? The verifier should show an appropriate message. If it doesn't, let's change it to do it. No point duplicating code. The verifier can handle relative paths too, what's the problem you've found?

**Comment by bethesque** [comment]
The paths need to be relative to the directory you run the executable from - that might have been the issue. So you need to invoke the verifier using the relative path from the project root if possible.

Btw, there's an issue to change the paths from options to space separated arguments, so we don't have to do the comma separating thing.

**Comment by mefellows** [comment]
Yeah from memory that was the problem, but I'm sure we can find a way to resolve it.

**Comment by mboudreau** [comment]
Fixed in 6.15.0.
