### ISSUE TITLE
Metadata object in pact file not standards compliant

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-node#38]
IN #34 we found a problem where the metadata section of the pact generated by my pact-js consumer tests is not compatible with the pact-jvm's PactReader.loadPact resolves the pact spec version.

This code in PactReader (from the master branch/latest version): 
```
 static Pact loadPact(Map options = [:], def source) {
    def pact = loadFile(source, options)
    def version = '2.0.0'
    def specification = pact.metadata?.'pact-specification'
    if (specification instanceof Map && specification.version) {
      version = specification.version
    }
    if (version == '3.0') {
        version = '3.0.0'
    }
    def specVersion = Version.valueOf(version)
    switch (specVersion.majorVersion) {
        case 3:
            return loadV3Pact(source, pact)
        default:
            return loadV2Pact(source, pact)
    }
  }
```

expects a metadata spec. version section that has this format:
```

"metadata": {
        "pact-specification": {
            "version": "x.x.x"
        }
```

BUT pacts generated from pact-js generates a metadata section that looks like this:
```

"metadata": {
    "pactSpecificationVersion": "3.0.0"
  }
```

See #34 and https://github.com/realestate-com-au/pact/issues/137 for background.

**Comment by mboudreau** [comment]
@mefellows is this still an issue and shouldn't this be lodged with pact-jvm than with pact-node?

**Comment by mefellows** [comment]
Looking through the threads, looks like we need to move to `pactSpecification.version` as per https://github.com/pact-foundation/pact-mock_service/commit/5b89d95167013ac4b11030b362c439f5632e7540

**Comment by mefellows** [comment]
Pact JS now generates metadata as per beow:

```json
  "metadata": {
    "pactSpecification": {
      "version": "2.0.0"
    }
  }
```

**Comment by mefellows** [comment]
... ☝️ as of a long time ago!
