### ISSUE TITLE
Can't install latests pact-node

### ISSUE THREAD

**Issue by bbarke** [pact-foundation/pact-node#47]
I get the following error when trying to install the latests pact version (5.0.0)

```
$ npm install --save-dev pact-web @pact-foundation/pact-node
npm ERR! path /path/to/node_modules/@pact-foundation/pact-node/bin/pact-cli.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/path/to/node_modules/@pact-foundation/pact-node/bin/pact-cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /path/to/.npm/_logs/2017-10-02T18_53_06_366Z-debug.log

```

**Comment by mboudreau** [comment]
@bbarke very sorry about that.  Will fix that ASAP.

**Comment by mboudreau** [comment]
@bbarke Damn, seems like npm is ignore *.js files because of what's been added in .gitignore, and since we don't have a .npmignore file, it uses the git one by default.  Changing that now.

Build is going out as we speak: https://travis-ci.org/pact-foundation/pact-node

**Comment by mboudreau** [comment]
@bbarke I've confirmed that this is now working with version 5.0.1.  Cheers.

**Comment by bbarke** [comment]
Thanks!

**Comment by mboudreau** [comment]
@bbarke Have you got it working alright?  v5 is a fairly major rewrite.
