### ISSUE TITLE
Change log

### ISSUE THREAD

**Issue by bbarke** [pact-foundation/pact-node#59]
By any chance is there a change log showing what has been committed/what has been resolved in the different versions?

**Comment by bbarke** [comment]
I could stop being lazy too and look at the commit history...

**Comment by mefellows** [comment]
@mboudreau would you be open to exploring the use of conventional changelog for `pact-node`? We could then steal the release process from `pact` which automates the generation of all of this, including version bumping etc.

**Comment by mboudreau** [comment]
Yeah, that sounds like an idea.  Would be good to track this in a better
fashion.

**Comment by mefellows** [comment]
FYI I have just added [conventional change log support](https://github.com/bcoe/conventional-changelog-standard/blob/master/convention.md) to our release process.

Have updated RELEASING.md and CHANGELOG.md to reflect this. Closing.
