### ISSUE TITLE
verifyProvider is adding a `Host` header of `example.org` when running a contract

### ISSUE THREAD

**Issue by ewortzman** [pact-foundation/pact-node#63]
When `verifyProvider` is run with a contract, a header of `"Host":"example.org"` is being added to the request that gets sent to the provider.  One of my services is failing its contract because of this, as it can't handle the header.

For example, when I run this contract:

```
{
  "consumer": {
    "name": "myconsumer"
  },
  "provider": {
    "name": "myprovider"
  },
  "interactions": [
    {
      "description": "A simple request",
      "providerState": "the service is up",
      "request": {
        "method": "get",
        "path": "/"
      },
      "response": {
        "status": 200
      }
    }
  ],
  "metadata": {
    "pactSpecification": {
      "version": "2.0.0"
    }
  }
}
```

The actual request that gets sent has these headers:

```
Host: example.org
Cookie:
X-Forwarded-For: 127.0.0.1
Content-Length: 0
```

**Comment by mefellows** [comment]
Can you please share your JS code? This doesn't sound right, it should pass through the hostname that is specified in `providerBaseUrl`.

**Comment by ewortzman** [comment]
```
const chai = require('chai')
const expect = chai.expect
const verifier = require('pact').Verifier
const request = require('request')

describe('Pact', () => {
  var opts = {
    providerBaseUrl: process.env.BASE_PATH,
    provider: 'myprovider',
    pactUrls: ['/home/vagrant/git/deployment-tool/test/contract/pact/deployment-tool-elmer.json']
  }

console.log(opts.providerBaseUrl)

  it('should verify', function () {
    this.timeout(5000)
    return verifier.verifyProvider(opts).then(output => {
      console.log('Pact Verification Complete!')
      console.log(output)
    })
  })
})
```

That log statement shows that `process.env.BASE_PATH` is set to "http://localhoist:8081"

**Comment by ewortzman** [comment]
```
const chai = require('chai')
const expect = chai.expect
const verifier = require('pact').Verifier
const request = require('request')

describe('Pact', () => {
  var opts = {
    providerBaseUrl: process.env.BASE_PATH,
    provider: 'myprovider',
    pactUrls: ['/path/to/myconsumer-myprovider.json']
  }

console.log(opts.providerBaseUrl)

  it('should verify', function () {
    this.timeout(5000)
    return verifier.verifyProvider(opts).then(output => {
      console.log('Pact Verification Complete!')
      console.log(output)
    })
  })
})
```

The log statement, and the fact that my server is receiving the requests, show that `process.env.BASE_PATH` is properly set.

**Comment by lirantal** [comment]
The Host header is defined in the RFC: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

**Comment by mefellows** [comment]
I'm guessing the problem is that the header is `example.org` instead of something else?

@ewortzman what is the value of process.env.BASE_PATH though?

**Comment by mefellows** [comment]
If possible, could you please provide us with a reproducible example? e.g. modify the example at https://github.com/pact-foundation/pact-js/tree/master/examples/e2e.

The relevant bit is here:

```
// Verify that the provider meets all consumer expectations
describe('Pact Verification', () => {
  it('should validate the expectations of Matching Service', function () {

    let opts = {
      provider: 'Animal Profile Service',
      providerBaseUrl: 'http://localhost:8081', // <------ this is what comes through
      ...
    }

    return verifyProvider(opts)
      .then(output => {
        console.log('Pact Verification Complete!')
        console.log(output)
      })
  })
})
```

**Comment by ewortzman** [comment]
`process.env.BASE_PATH` is the url of my running service. In this case, it, coincidentally, `http://localhost:8081`.  But I've run the verifier with different base urls and I always get the `example.org` header. 

And yes, I believe the problem is that the Host header should contain the url of the request's destination (i.e. the `providerBaseUrl`) but it actually contains `example.org`.

**Comment by ewortzman** [comment]
running the example in the provided vagrant box give me the same issue. Using `tcpdump`, I can see that the first `GET /animals/available` request contains the `Host: example.org` header.

**Comment by mefellows** [comment]
@mboudreau could you please cast your eyes over this too? I'm not seeing this header, but perhaps it's my setup interfering with it. Would be good to see if you can repro it.

**Comment by mboudreau** [comment]
@ewortzman Could you please paste your package.json dependency versions?  If you can give us a code dump of your example not working, that would be greatly appreciated to help debug this further.

If there is an issue somewhere, it would be with our Ruby standalone.  I'll go digging through that code to see if anything comes up.

**Comment by mboudreau** [comment]
Also, I've looked through our [whole organization for any reference for example.org](https://github.com/search?utf8=%E2%9C%93&q=org%3Apact-foundation+%22example.org%22&type=Code).  There are many, but all around tests and examples, but in the end code itself.

Not to sound skeptical, but I would imagine if this was an issue, it would have affected more people by now.  I'm guessing there is something wonky with your setup, hence the need to have a workable example for us to debug what's actually going on.

**Comment by ewortzman** [comment]
I'm trying to replicate it on a different machine, and you're right. I can't.  Must be something with my setup.  I'll close this issue.

**Comment by mboudreau** [comment]
I'm still curious about what happened to cause this, so if you discover it,
please let us know.  Cheers :)
