### ISSUE TITLE
TypeScript compilation fails due to missing type definitions

### ISSUE THREAD

**Issue by zsims** [pact-foundation/pact-node#69]
This is a carry on from pact-foundation/pact-js#142

## Software versions

* **OS**: Ubuntu 16.04.3 LTS
* **Consumer Pact library**: PactJS 5.3.1
* **Node Version**: v6.9.1

## Expected behaviour
When using pact-js as a `devDependency`, pact-js can be compiled by TypeScript successfully without requiring additional definitions (e.g. adding `@types/bunyan` as an explicit dependency).

## Actual behaviour
TypeScript compilation fails.

## Steps to reproduce

 1. Clone/Download https://gist.github.com/zsims/904dcb7d7fcc2543776740be65b171c0
 2. `yarn install` (or `npm install`)
 3. `yarn test` (or `npm test`)

## Relevant log files

```
$ yarn run test
yarn run v1.3.2
$ tsc
node_modules/@pact-foundation/pact-node/src/logger.ts(11,8): error TS2339: Property 'info' does not exist on type 'Logger'.
node_modules/@pact-foundation/pact-node/src/logger.ts(19,36): error TS2339: Property 'level' does not exist on type 'Logger'.
node_modules/@pact-foundation/pact-node/src/logger.ts(25,16): error TS2554: Expected 0 arguments, but got 1.
node_modules/@pact-foundation/pact-node/src/publisher.ts(10,3): error TS2322: Type '{}' is not assignable to type 'PublisherOptions'.
  Property 'pactFilesOrDirs' is missing in type '{}'.
error Command failed with exit code 2.
```

**Comment by zsims** [comment]
So the reproduction still fails due to `tsc` picking up the source from the package (instead of just the definitions). Per Microsoft/TypeScript#7432 a recommended way to avoid this is to stop publishing the sources. I'll raise a PR.

**Comment by mboudreau** [comment]
@zsims has this been fixed with 6.7.3?

**Comment by zsims** [comment]
@mboudreau Sorry, had reverted to using it without types. I'll update and confirm within the next day.

**Comment by zsims** [comment]
@mboudreau Can confirm this package works fine under TypeScript. But, a new release is needed for `pact-foundation/pact-js` due to the fixes that recently landed regarding `es6-promise`.

I can confirm that master of this repo and master of `pact-foundation/pact-js` work well from TypeScript 😄

**Comment by mefellows** [comment]
Running a release for this now @zsims. `v5.3.2` should be out in the next hour or so.

**Comment by zsims** [comment]
@mefellows sorry for the delay, I can confirm v5.3.2 works a treat. This issue can probably be closed now.
