### ISSUE TITLE
Verifier doesn't return error information to client

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-node#7]
[Currently](https://github.com/pact-foundation/pact-node/blob/master/src/verifier.js#L90-L107) we only log Verifier output (using Bunyan), it would be preferable to have the output returned in the promise chain so that we can properly handle it in downstream libs (pact-js, mocha etc.). The current message 'Pact Verification failed' is insufficient information, and too late to make a programmatic call to output logs.

When things succeed, this data is generally not required and is noise, but when things fail we need to be able to programatically access that information.

I suggest we pipe the stderr/out to a variable and return it in the promise rejection (and success) at https://github.com/pact-foundation/pact-node/blob/master/src/verifier.js#L104.

**Comment by mboudreau** [comment]
@mefellows is this good to be closed?

**Comment by mefellows** [comment]
Yep!
