### ISSUE TITLE
Is there a version that can be used with AngularJS 1.X?

### ISSUE THREAD

**Issue by softengi** [pact-foundation/pact-node#73]
Hi,

Is there a version of pact-node that can be used with AngularJS version 1.6?

Thanks in advance.

**Comment by mefellows** [comment]
Hi @softengi, what is your use case and what is the problem you are having? have you looked at https://github.com/pact-foundation/pact-js/?

**Comment by mefellows** [comment]
@softengi I'm going to close this. If you have more detail on your issue we can re-open and discuss. For now, as I know of no reason as to why Pact couldn't be compatible with Angular 1.6 I'm going to close this.
