### ISSUE TITLE
Cannot find module './build/Release/DTraceProviderBindings' from 'dtrace-provider.js'

### ISSUE THREAD

**Issue by mbark** [pact-foundation/pact-node#74]
Running `pact` in `jest` I get the error:
```
Error: Cannot find module './build/Release/DTraceProviderBindings' from 'dtrace-provider.js'
[...]
```

This seems to be the same problem as the one mentioned in [issue 63 for `pact-js`](https://github.com/pact-foundation/pact-js/issues/63), which according to @mefellows is an upstream problem with `pact-node`, therefore I'm raising the issue here.

The `node-bunyan` [issue mentioned](https://github.com/trentm/node-bunyan/issues/525) in the thread states that the problem has been fixed in `dtrace-provider@0.8.6`. As far as I can tell it should therefore be sufficient to upgrade from `bunyan` version `1.8.2` to `1.8.4` to resolve this problem.

**Comment by mefellows** [comment]
Thanks for looking into this, hopefully it's an easy one!

**Comment by mboudreau** [comment]
yep, project is probably due to upgrade all dependencies anyways.  I'll take care of this.

**Comment by mboudreau** [comment]
@mbark Version 6.10.1 going out as we speak that will fix this issue.

**Comment by mbark** [comment]
Thanks for the fast response @mboudreau! Now `pact-js` just needs a patch with the updated `pact-node` version and we can close that issue as well 🎉
