### ISSUE TITLE
Inconsistency in tagging pacts while publishing to broker

### ISSUE THREAD

**Issue by shiri134** [pact-foundation/pact-node#77]
We are trying to tag pact files, but the only first found pact file is tagged.
`import pact from '@pact-foundation/pact-node';`

`const opts = {`
  `pactFilesOrDirs: [${__dirname}/../../../pacts/*/],`
 ` pactBroker: brokerurl,`
  `pactBrokerUsername: brokerusername,`
`  pactBrokerPassword: brokerpassword,`
  `consumerVersion: '1.0.0',`
`  tags : ['prod', 'test']`
`};`

`pact.publishPacts(opts)`
  `.then(() => {})`
`.catch(e => {`
 ` console.error('Pact contract publishing failed: ', e);`
  `process.exit(1);`
`});`
Any idea how to solve this issue?

**Comment by mefellows** [comment]
How do you know only the first found pact file is found? Can you please describe what you are seeing in more detail? What pacts do you have in that folder?

If you download the `pact-broker` binary at https://github.com/pact-foundation/pact-ruby-standalone/releases and use it to publish, do you get the same result? If so, it may actually be operating correctly. It's the version resource that is tagged, not the pact. Have a read of:

* https://github.com/pact-foundation/pact_broker/wiki/Overview
* https://github.com/pact-foundation/pact_broker/wiki/Using-tags

**Comment by shiri134** [comment]
We have multiple providers for single consumer, for that we are creating pact files as below to distinguish each other.
consumer1-navigation-service 
consumer1-store-service, 
consumer2-add-to-cart, 
consumer2-recommendation-service
consumer3-recommendation-service
consumer3-srp-svc

When try to publish these, as pact-broker got consumer2 as first as below log shows,

![image](https://user-images.githubusercontent.com/20062012/37583545-d2d0d356-2b77-11e8-8c69-5c2b180ca2fe.png)

So only, consumer2-add-to-cart, consumer2-recommendation-service are tagged but not others as below
![image](https://user-images.githubusercontent.com/20062012/37583576-f7b6fa06-2b77-11e8-9661-e9775bf9b0cb.png)

To prove this hypothesis, we tried to have only below pacts
consumer1-navigation-service 
consumer1-store-service, 
consumer3-recommendation-service
consumer3-srp-svc

When try to publish these, as pact-broker got consumer1 as first as log shows

![image](https://user-images.githubusercontent.com/20062012/37583650-451fcf70-2b78-11e8-8907-97cf562d3063.png)

So only, consumer1-navigation-service , consumer1-store-service are tagged but not other as below,
![image](https://user-images.githubusercontent.com/20062012/37583691-6b3977ba-2b78-11e8-996a-27597f4d880e.png)

Please help us.

**Comment by bethesque** [comment]
Something that strikes me as strange in your publishing code is that you're publishing pacts for different consumers at the same time. This is very unusual. Usually, you would generate the pacts for a consumer, and then publish the pacts for that consumer. 

Can you explain your set up?

**Comment by bethesque** [comment]
As an aside, can I get you to read these docs on pacticipant version numbers? The numbers you're currently using will cause you problems https://github.com/pact-foundation/pact_broker/wiki/Pacticipant-version-numbers

**Comment by shiri134** [comment]
@bethesque here we have single consumer application, but in different parts of application we are using different providers, to distinguish between different pacts generated we are naming them differently, but they belong to same consumer application.

**Comment by bethesque** [comment]
You have named them "consumer1", "consumer2" and "consumer3" - if these are pacts for the same consumer, you need to give them the same name. The pacts will already be distinguished from each other by the fact that the provider is different. It is assumed by the entire tool chain that one consumer may have multiple providers, and vice versa. The entire underlying data model will be incorrect if you give the same consumer different names for different pacts. Closing, as there is no bug here. Please let me know if you need further explanation.

**Comment by shiri134** [comment]
Thank you, we modified all pacts to same consumer name as per the suggestion and we were able to tag them all.
