### ISSUE TITLE
Update error message for local files 

### ISSUE THREAD

**Issue by saschak094** [pact-foundation/pact-node#78]
When adding local json files with the provider option pactFilesOrDirs, I receive an error: 
```bash
Error: Must provide the pactFilesOrDirs argument if no brokerUrl provided
```

Shouldn't the error message look like: 
```bash
Error: Must provide the pactUrls argument if no brokerUrl provided
```

**Comment by mefellows** [comment]
Is this for publishing pacts?

If you take a look at the [file](https://github.com/pact-foundation/pact-node/blob/master/src/publisher.ts#L86), `pactFilesOrDirs` is the correct argument. 

Have you got an outdated version?

**Comment by michalboo** [comment]
I ran into what seems like this issue when playing around with the `e2e` example in the pact-js repo.

The commented-out example of using a local pact file for provider verification at https://github.com/pact-foundation/pact-js/blob/39dfc45c5fa54b9a8f1c284f7b7f1873fcea0512/examples/e2e/test/provider.spec.js suggests using an array of filepaths under a `pactFilesOrDirs` key.

After un-commenting this option (and commenting out the pact broker-related one), running the provider spec started throwing `Error: Must provide the pactFilesOrDirs argument if no brokerUrl provided`.

This lead to following the stacktrace to: https://github.com/pact-foundation/pact-node/blob/2f20b783d9a12f0a94b220d7d0a151a20314a3df/src/verifier.ts#L65-L67 (It looks like the error message mentions an argument which is not really part of the `if` check above it.)

Changing the option key from `pactFilesOrDirs` to `pactUrls` resolved the issue for me.

Please see https://gist.github.com/michalboo/a80ab0c20c2e5f2220a87fd8e80bd781 for an example of failing/passing opts objects + the error/stacktrace I saw.

**Comment by mefellows** [comment]
Ideally, we keep that key consistent with the other parts of the project `pactFilesOrDirs` is consistent, unlike `pactUrls`. But I don't want to break backward compatibility again, so for now I've just fixed the messaging. Thanks for bringing to our attention.

**Comment by mefellows** [comment]
`v6.14.3` should be on its way up in the next little bit.
