### ISSUE TITLE
pact-node fails to launch mock server on windows

### ISSUE THREAD

**Issue by bbarke** [pact-foundation/pact-node#90]
We are using pact-node (v6.16.0) bundled with pact-karma (2.1.5) and pact-web (5.9.0)

When trying to run the pact tests on a windows machine, I'm seeing the following error
```
[2018-05-07T22:23:19.539Z]  INFO: pact-node@6.16.0/7872 on xxxxxx: Created 'standalone\win32-1.38.0\bin\pact-mock-service.bat service --port '3110' --consumer 'consumer' --prov
ider 'provider' --log 'C:\.....\pacts\stubserver-integration.log' --pact_dir '.....\pacts' --pact-file-writ
e-mode 'overwrite' --host 'localhost'' process with PID: 8688
[2018-05-07T22:23:24.034Z]  WARN: pact-node@6.16.0/7872 on xxxxxx: Pact exited with code 1.
[2018-05-07T22:23:24.036Z]  INFO: pact-node@6.16.0/7872 on xxxxxx: Removing Pact with PID: 8688
ERROR: The process "8688" not found.
```

When trying to run that bat file directly, I get the following error
```
C:\.....\node_modules\@pact-foundation\pact-node\standalone\win32-1.38.0\bin>pact-mock-service.bat
C:\.....\node_modules\@pact-foundation\pact-node\standalone\win32-1.38.0\lib\ruby\bin\..\bin.real\ruby.exe: No such file or directory -- UI (LoadError)
```

Any pointers on why this is happening?

**Comment by mefellows** [comment]
Hmm could you please share your Windows environment details?

Which shell are you running it on?

**Comment by mboudreau** [comment]
@bbarke was there any issues with your install process? There's a postinstall that runs and downloads the binary files needed for your OS.  Maybe just try to reinstall it using `npm uninstall @pact-foundation/pact-node; npm install @pact-foundation/pact-node`.

**Comment by bbarke** [comment]
This is on Windows 10 with the regular windows terminal. 

It looks like the issue was because the location/path of the project had a space in it, for example:

`C:\MY UI\angular-project\` it was failing because it didn't handle the space and tried to run 'UI as an argument, resulting in 'no such file or directory -- UI'

**Comment by mboudreau** [comment]
@bbarke wait, pact-node didn't work because of the space or just the .bat command?  Because if it's the former, there's definitely an issue which shouldn't happen.  Can you please confirm?

**Comment by bbarke** [comment]
Yes I can confirm this. I renamed a working pact project path to have a space in it, and pact failed to launch. I changed the name back to to not have a space, and it started working again.

**Comment by mboudreau** [comment]
@bbarke my question is, are you talking about using the command line to hit the .bat file, or using the pact-node CLI/API?  Because if it's the latter, that's a bug that needs to be fixed.

**Comment by bbarke** [comment]
I'm using karma-pact, which uses the node CLI/API to start the pact stub server.

**Comment by mboudreau** [comment]
huh, okay.  This might be a bug then.  I'll have to investigate further,
but I'm guessing it has something to do with the shell script running that
wrapping it in quotes.

**Comment by TimothyJones** [comment]
@mboudreau, if quoting is indeed the issue, then the investigation here might be useful: https://github.com/pact-foundation/pact-js/issues/160

**Comment by mboudreau** [comment]
Yep, spot on. I'll fix this today if I can.

**Comment by mboudreau** [comment]
@bbarke very sorry I haven't gotten to this yet.  It's been hectic at work with GDPR :/

**Comment by mboudreau** [comment]
@bbarke good news, version 6.18.3 is going out as we speak with the windows path fixes.  Please let us know how you go.  Cheers.

**Comment by mefellows** [comment]
Thanks Michel!

**Comment by bbarke** [comment]
Thank you!

**Comment by AndrewSerie** [comment]
We are running `pact-node 6.19.6` `karma-pact 2.1.5` and `pact-web 5.9.1`

Is there a max path length requirement? I seem to be having issues with running pact tests with directories that are long.  After I change the length of the directory names, pact-node starts up successfully.  

After running on windows machine with long path names:
```
Creating Pact Server with options:
    consumer = ux,
    provider = core,
    logLevel = debug,
    dir = C:\Users\aserie\source\repos\my-long-repo-name\long-workspace-name\apps\app1\pacts,
    log = C:\Users\aserie\source\repos\my-long-repo-name\long-workspace-name\apps\app1\logs\pact.log,
    port = 1234,
    host = localhost,
    pactFileWriteMode = overwrite,
    ssl = false,
    cors = false
[2018-07-16T14:34:57.615Z]  INFO: pact-node@6.19.6/10772 on L-19412-1: Created 'standalone\win32-1.52.1\bin\pact-mock-service.bat service --consumer 'ux' --provider 'corerunner' --log-level 'DEBUG' --pact_dir 'C:\Users\aserie\source\repos\my-long-repo-name\long-workspace-name\apps\app1\pacts' --log 'C:\Users\aserie\source\repos\my-long-repo-name\long-workspace-name\apps\app1\logs\pact.log' --port '1234' --host 'localhost' --pact-file-write-mode 'overwrite'' process with PID: 6308
(node:10772) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
[2018-07-16T14:35:04.536Z]  WARN: pact-node@6.19.6/10772 on L-19412-1: Pact exited with code 1.
[2018-07-16T14:35:04.536Z]  INFO: pact-node@6.19.6/10772 on L-19412-1: Removing Pact with PID: 6308
ERROR: The process "6308" not found.                                                               
```

Simply making the directory smaller will start pact-node without it exiting with code 1.
Shorter directory name: C:\Users\aserie\source\repos\my-repo\workspace\apps\app1\...
