### ISSUE TITLE
Do not fail installation when Google Analytics call fails

### ISSUE THREAD

**Issue by sbaechler** [pact-foundation/pact-node#91]
I had trouble installing pact. I kept getting the following error:

```
> @pact-foundation/pact-node@6.16.1 postinstall /Users/bao/.nvm/versions/node/v8.9.1/lib/node_modules/@pact-foundation/pact-node
> node postinstall.js

Installing Pact Standalone Binary for darwin.
Downloading Pact Standalone Binary v1.43.0 for platform darwin from https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.43.0/pact-1.43.0-osx.tar.gz
Please note: we are tracking this download anonymously to gather important usage statistics. To disable tracking, set 'DO_NOT_TRACK=true' as an environment variable.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 0.0.0.0:443
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
```

Only when I set `DO_NOT_TRACK=true` the installation worked. I believe that the call to Google Analytics failed.

Please add a catch clause to that call so it does not break the installation if the call fails.

**Comment by mefellows** [comment]
@mboudreau I thought you [checked](https://github.com/pact-foundation/pact-node/pull/87#commitcomment-28642948) that as part of [this PR](https://github.com/pact-foundation/pact-node/pull/87)?

As in, tested the graceful degradation?

**Comment by mboudreau** [comment]
It should be a fire and forget. I'll check it again to be sure.

**Comment by mboudreau** [comment]
@sbaechler Why is it pointing to 0.0.0.0:443? Do you have a funky setup?

**Comment by mboudreau** [comment]
@sbaechler Eh, doesn't matter either way, I've added something to ignore errors that might arise.  The fix will be out with 6.16.2

@mefellows it seems that my understanding of the node HTTP client was lacking when it came to error handling.  Apparently, if you don't handle it via a listener, it actually bubbles up and errors out at the process level, which is weird because it actually doesn't seem to 'throw' anywhere.

**Comment by mefellows** [comment]
I'll admit I saw the code and in passing thought something similar. Thanks for fixing!

**Comment by mefellows** [comment]
It's common to run local proxies in Corp/Enterprise environments, where localhost proxies out (often via other intermediate proxies - proxyception!). But that might have just been a test to see what happened.

**Comment by sbaechler** [comment]
I forgot, I block trackers in the hosts file using [hBlock](https://github.com/zant95/hBlock). That's why the Google Analytics call failed.

**Comment by mboudreau** [comment]
Ah, that's why.  Either way, it's a good edge case for us, and it should
fail gracefully :)
