### ISSUE TITLE
Pact-broker behind reverse proxy - Unable to publish and verify provider

### ISSUE THREAD

**Issue by loheswaran** [pact-foundation/pact-node#93]
I have set up pact broker behind a reverse proxy.  Getting error while trying to publish and verify the 
pact.  The same works with non-ssl URL

**Pact publish error log :**

```
Could not publish pact:
    Error making request - OpenSSL::SSL::SSLError SSL_connect returned=1 errno=0 state=error: certificate verify failed /Users/loheswaran_g/Work/wag-src-repo/fork/boilerplate/react-ui-boilerplate/node_modules/@pact-foundation/pact-node/standalone/darwin-1.43.1/lib/vendor/ruby/2.2.0/gems/pact_broker-client-1.14.1/lib/pact_broker/client/pacts.rb:35:in `get', attempt 1 of 3
```

**Pact verify provider error log :**

```
Error: the string "Unable to find pacts for given provider 'APIHealthCheckService' and tags ''" was thrown, throw an Error :)
      at tryCatch (node_modules/es6-promise/dist/lib/es6-promise/-internal.js:188:12)
      at invokeCallback (node_modules/es6-promise/dist/lib/es6-promise/-internal.js:203:13)
      at publish (node_modules/es6-promise/dist/lib/es6-promise/-internal.js:177:7)
      at publishRejection (node_modules/es6-promise/dist/lib/es6-promise/-internal.js:118:3)
      at flush (node_modules/es6-promise/dist/lib/es6-promise/asap.js:92:5)
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by mefellows** [comment]
This is unrelated to pact-node, my guess is that you have a self-signed SSL certificate that the Node JS runtime is not aware of, and is complaining about not trusting the unverified SSL certificate.

You'll need to ensure the node process that runs the publish step has been setup with the correct SSL configuration.

**Comment by loheswaran** [comment]
I am not seeing an option to pass the SSL certificate in publish and verify provider API.

<img width="873" alt="screen shot 2018-05-21 at 6 38 51 pm" src="https://user-images.githubusercontent.com/8875426/40309270-84fa5a18-5d26-11e8-87c0-54d62f34e4a0.png">
<img width="718" alt="screen shot 2018-05-21 at 6 39 33 pm" src="https://user-images.githubusercontent.com/8875426/40309271-855aa1d4-5d26-11e8-95c5-62e96f2b796a.png">

**Comment by mefellows** [comment]
Sorry @loheswaran I incorrectly believed the node Process was responsible for the certificate management, which either way, would not have been an option there (it would be a _node_ option, not a _pact_ one).

We currently don't support this via Node, your options:
* Disable SSL if it's only accessible internally anyway
* [publish your pacts manually](https://github.com/pact-foundation/pact_broker/wiki/Publishing-and-retrieving-pacts#publishing) 

cc: @bethesque for potential future feature req.

**Comment by bethesque** [comment]
https://github.com/pact-foundation/pact-ruby-standalone/releases#pact-broker-client

> To connect to a Pact Broker that uses custom SSL cerificates, set the environment variable $SSL_CERT_FILE or $SSL_CERT_DIR to a path that contains the appropriate certificate.

**Comment by loheswaran** [comment]
@bethesque, I tried setting **SSL_CERT_FILE** environment variable.  Now I am able to publish the pacts to the broker but verify pact is still failing. Please find below for pact verify error log

`Error: the string "Unable to find pacts for given provider 'APIHealthCheckService' and tags ''" was thrown, throw an Error :)`

The document shows that pact verify supports local and networked (http-based) files.  It seems pact verify doesnt support files over https even if we pass **SSL_CERT_FILE** environment variable

<img width="752" alt="screen shot 2018-05-22 at 5 02 33 pm" src="https://user-images.githubusercontent.com/8875426/40360050-61802182-5de2-11e8-90b2-7ec9c3619a29.png">

**Comment by bethesque** [comment]
Can you locate the ruby standalone package inside your node package, and then find the README.md. Inside, you will find all the version numbers of the gems included. Can you copy paste them here?

**Comment by bethesque** [comment]
Actually, @mefellows, given that the pact-provider-verifier only currently accepts URLs, the js code must be using the broker API to look up the pact URLs to pass in to it (though we will be adding this soon, one of the DiUS people is working on the code for this). I believe this is back to you now.

**Comment by mefellows** [comment]
Which takes me back to my original [comment](https://github.com/pact-foundation/pact-node/issues/93#issuecomment-390648521). This is a node TLS configuration, I haven't tested myself but in theory adding your CA and/or self-signed certificate to the NodeJS runtime configuration should be all that is required.

**Comment by mefellows** [comment]
Thanks @loheswaran, however it's not the provider verifier that is currently the issue.

`Unable to find pacts for given provider` is an error in Pact Node, which is fetching the pacts from the broker and _then_ passing on to the verifier. There is no Ruby process doing this.

The first step is to configure **Node JS** to accept your self-signed certificate, which you should be able to Google and find an approach that works for your setup.

Step 2 is to then still configure the verifier (as per your previous demo) with the settings. If that fails, then you can proceed to testing that the `pact-provider-verifier` is able to pull pacts down directly with a URL in the broker, rather than via pact-node as you currently have demonstrated.

**Comment by mefellows** [comment]
@loheswaran I'm just speculating, but [these lines](https://github.com/pact-foundation/pact-node/blob/master/src/broker.ts#L40-L83) of code is what goes out to the Pact Broker to fetch pacts.

Given that your broker is running with a self-signed certificate, the NodeJS runtime is not able to trust it without some configuration telling it that it is safe - I'm guessing that this is the cause of your issues, given that it works just fine over http.

Modifying the [NodeJS configuration](https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file) to specify your own custom CA is what you want.

**Comment by mefellows** [comment]
@loheswaran any update?

**Comment by mboudreau** [comment]
I'm going to close this for now.  I haven't heard anything from @loheswaran in a while.  If this is still a problem, we'll reopen this ticket.

**Comment by lirantal** [comment]
@mefellows may we open this again?

at least it seems that I'm getting the same issue of "Unable to find pacts for given provider" when my broker URL is HTTP-only. Is SSL a requirement?

**Comment by mefellows** [comment]
This issue as I understand it, is that he is using a broker behind http with his own self-signed certificate, and (unfortunately), multiple parts to the Pact ecosystem need to be aware that this is a trustworthy certificate.

Perhaps open another issue if you're having trouble with http? I'm not aware of any restrictions against http-only brokers (as in, it should definitely work).

**Comment by bhcmoney** [comment]
What worked for me:

To publish with `pact-node` or `pact-js` do the following:

Download your certificate chain that your broker is using. If pulled right out of chrome you will most likely have `.cer` files.

For example: 
- root.cer
- intermediate.cer
- ssl_certificate.cer

Convert those `.cer` files to `.crt` files by doing:
- `$ openssl x509 -inform DER -in root.cer -out root.crt`
- `$ openssl x509 -inform DER -in intermediate.cer -out intermediate.crt`
- `$ openssl x509 -inform DER -in ssl_certificate.cer -out ssl_certificate.crt`

Then for ruby to recognize it properly it must be a bundle, so let's bundle these together similar to the `ca-bundle.crt`
- `$ cat root.crt intermediate.crt ssl_certificate.crt > ca-bundle.crt`

Now within your javascript you must set the `SSL_CERT_FILE` that the standalone mentions. Make sure the `certPath` variable resolves to the correct path:

```javascript
const path = require("path");
const publisher = require("@pact-foundation/pact-node");

const certPath = path.resolve(__dirname, "../ca-bundle.crt");
console.log(certPath);
process.env.SSL_CERT_FILE = certPath;

const opts = {
  providerBaseUrl: "/",
  pactFilesOrDirs: [path.resolve(process.cwd(), "pacts")],
  pactBroker: "<your_https_broker_url>",
  consumerVersion: "1.0.0"
};

publisher.publishPacts(opts).then(() => console.log("Pacts successfully published"));
```
