### ISSUE TITLE
Please update standalone to 1.45.0

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-node#96]
There is a new option `--log-level` in the pact-mock-service. Can this be exposed in the js config please. Options are DEBUG, INFO, WARN, ERROR. It defaults to DEBUG if no option is given.

This is for: https://github.com/pact-foundation/pact-mock_service/issues/91

**Comment by mefellows** [comment]
Yep, we'll lock it to what we expose via Pact Node and Pact JS.

**Comment by mboudreau** [comment]
Done, version 6.19.0 out.
