### ISSUE TITLE
Error with pattern matcher

### ISSUE THREAD

**Issue by shavo007** [pact-foundation/pact-node#99]
I have added in pattern matching to my interaction.

When i run pact verification it works fine.

But i see a warn in the console for pact broker

` WARN: Ignoring unsupported matching rules {"min"=>1} for path $['body']['Advertisers']`

I use `eachLike` on an array 

```
	Advertisers: eachLike({
		Name: 'Account'
	})
```

Deps:

```
    "@pact-foundation/pact": "5.9.1",
        "@pact-foundation/pact-node": "^6.19.4",
```

pact broker : dius/pact-broker:latest

Thanks,
Shane.

**Comment by bethesque** [comment]
I am actually just fixing that at the moment. Ignore the warning, the min is being used. The warning will be gone in the next release.

**Comment by mboudreau** [comment]
Next release will be out in the next few hours :)

**Comment by shavo007** [comment]
let me know @mboudreau  and ill test it out

**Comment by mboudreau** [comment]
Sorry, we hit a small snag because the latest binary changed something
slightly.  We're currently in the process of fixing it and will release a
new version soonish.  Cheers.

**Comment by mefellows** [comment]
6.19.5 on its way out folks, stand by.

**Comment by shavo007** [comment]
🚀
